ignoredBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-solid-svg-icons'
  - canvas
  - unrs-resolver

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
