// Task types
export enum TaskStatus {
  PENDING = 'pending',
  ASSIGNED = 'assigned',
  IN_PROGRESS = 'in_progress',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
}

export enum TaskPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent',
}

export interface Task {
  id: number;
  task_id: number;
  exam_center_code: number;
  class_group: number;
  class_level: number;
  eval_center_id: number;
  processing_status: 'pending' | 'assigned' | 'complete' | 'graded' | 'exported';
  registered_amount: number;
  present_amount: number;
  actual_sheet_count: number;
  assigned_user_id: number | null;
  error_count: number;
  latest_batch_id?: number;
  err_duplicate_sheets_count?: number;
  err_low_answer_count?: number;
  err_student_id_count?: number;
  err_exam_center_id_count?: number;
  err_class_group_count?: number;
  err_class_level_count?: number;
  created_at: string;
  access_source?: string;

}

export interface TaskStats {
  registered_total: number;
  present_total: number;
  actual_sheets_total: number;
  error_total: number;
  err_duplicate_sheets_total: number;
  err_low_answer_total: number;
  err_student_id_total: number;
  err_exam_center_id_total: number;
  err_class_level_total: number;
  err_class_group_total: number;
}

export interface CreateTaskRequest {
  // Not fully defined in guide, keeping minimal or removing if unused.
  // Assuming tasks are generated by backend, but maybe needed for testing.
  // Note: fully generated from Legacy system using MySQL UDFs.
  exam_center_code: number;
  class_level: number;
  eval_center_id: number;
}

export interface TaskAssignmentRequest {
  user_id: number;
  permission_level: 'view' | 'upload' | 'manage';
  eval_center_id?: number;
  class_level?: number;
  task_ids?: number[];
}

export interface TaskDistributionRequest {
  // Keeping as is or removing if not used in Phase 3. 
  // Guide doesn't mention distribution strategy anymore, just assignment.
  // Leaving it for now but updating types to number.
  // Note: Update in future as enhancement feature.
  task_ids: number[];
  user_ids: number[];
  strategy: 'fair' | 'workload' | 'random';
}
